joy:
  ros__parameters:
    # device_name: Sony Interactive Entertainment Wireless Controller
    # device_name: Wireless Controller
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 1.0
          offset: 0.0
        drive-steering_angle:
          axis: 3
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /allow_autonomous
      deadman_buttons: [5]
      message_value:
        data:
          value: false

    respawn_robot:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /respawn_robot
      deadman_buttons: [2]
      message_value:
        data:
          value: false
