camera:
    ros__parameters:    
      depth_module:
        profile: 640x480x30 
      rgb_camera:
        profile: 640x480x30 
      enable_depth: true
      enable_color: true
  
      enable_infra1: false
      enable_infra2: false
      enable_sync: false
      infra_rgb: false
      initial_reset: false
  
      colorizer:
        enable: false 
      pointcloud:
        enable: true
        allow_no_texture_points: true 
  
      enable_accel: false 
      enable_gyro: false
      gyro_fps: 200
      accel_fps: 63
      clip_distance: -2.
      linear_accel_cov: 0.01
      tf_publish_rate: 0.0
  
      decimation_filter:
        enable: true
      disparity_filter:
        enable: false
      temporal_filter:
        enable: true
      hole_filling_filter:
        enable: true
      spatial_filter:
        enable: true
      align_depth:
        enable: true
  
      wait_for_device_timeout: -1.0
      reconnect_timeout: 6.0